### ISSUE TITLE
Sqlite database persistence with Docker

### ISSUE THREAD

**Issue by c9482** [elsa-workflows/elsa-core#5054]
Hello,

I am trying to persist the sqlite database using docker-compose. Despite overriding the connection string as shown below, the application still starts with the default connection string from appsettings.json. What am I missing? Many thanks in advance.

```
elsa-server-and-studio:
    image: elsaworkflows/elsa-server-and-studio-v3:latest
    container_name: elsa-server-and-studio
    volumes:
      - elsa-db:/app/data
    ports:
      - 13000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_CONFIG=./app/appsettings.json
      - ConnectionStrings__SqlLite=Data Source=/app/data/elsa.sqlite.db;Cache=Shared;
      # This does not work either
      # - ConnectionStrings:SqlLite=Data Source=/app/data/elsa.sqlite.db;Cache=Shared;
```

**Comment by c9482** [comment]
I modified the service definition as recommended but it did not solve my problem. 

```
version: "3"

volumes:
  elsa-db: {}

  elsa-server-and-studio:
    image: elsaworkflows/elsa-server-and-studio-v3:latest
    container_name: elsa-server-and-studio
    volumes:
      - elsa-db:/app/data
    ports:
      - 13000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Elsa__ConnectionStrings__SqlLite=${ELSA_CONNECTION_STRING}
```

Also, I do not see "elsa" section in the appsettings.config. The file looks like this:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Elsa.Mediator": "Warning",
      "MassTransit": "Warning",
      "Microsoft.Extensions.Http": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.EntityFrameworkCore": "Warning",
      "Microsoft.AspNetCore": "Warning",
      "System.Net.Http": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "Sqlite": "Data Source=elsa.sqlite.db;Cache=Shared;",
    "RabbitMq": "rabbitmq://guest:guest@localhost:5672"
  }
}
```
Is there anything else I can try?
