### ISSUE TITLE
[BUG] Mixed Content block after deployed to kubernetes 

### ISSUE THREAD

**Issue by hkng** [elsa-workflows/elsa-core#5599]
## Description

Deploy elsa workflow docker into kubernetes, some content will redirect from https to http
for example: it contains http://xxx.xxx.com/package/version content (not https)

## Steps to Reproduce
Docker version: elsaworkflows/elsa-server-and-studio-v3
Use Kubernetes ingress setting as below:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwss-workflow-ingress
  namespace: dwss-dev
  annotations:   
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
   # Use ssl
  tls:
  - hosts:
    - xxx.xxx.com
    secretName: hiphing-com-hk-cert
  rules:
  - host: xxx.xxx.com
    http:
      paths:
      - pathType: Prefix   
        path: "/"
        backend:
          service:
            name: elsa-workflow
            port:
              number: 8080

```
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwss-workflow
  namespace: dwss-dev
  labels:
    app: dwss-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwss-workflow
  template:
    metadata:
      labels:
        app: dwss-workflow
    spec:   
      containers:
      - name: elsa-workflow
        image: elsaworkflows/elsa-server-and-studio-v3:latest
        imagePullPolicy: Always      
        env:        
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: HTTP_PORTS
            value: "8080"     
          - name: ELSASERVER__URL
            value: https://localhost:7043/elsa/api
          # Base URL for the server
          - name: HTTP__BASEURL
            value: https://dwss-wf-dev.hiphing.com.hk
          - name: ELSA__SERVER__BASEURL
            value: "https://dwss-wf-dev.hiphing.com.hk/"         
          - name: ASPNETCORE_URLS
            value: http://+:8080       
        ports:
           - containerPort: 8080
             protocol: TCP

```

HTTP call to http://xxx.xxx.com/package/version and "Mixed Block" by browser

Refer to attachment below:
![elsa-bug](https://github.com/elsa-workflows/elsa-core/assets/14144067/01ebc14d-b971-4628-8038-9205c43655c7)
## Expected Behavior
No mixed content. only https

## Actual Behavior
Mixed content. some https and some http
