### ISSUE TITLE
[DOC] Docker deployment of elsa 3

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#6150]
### Documentation Issue Overview
I use traefik as HTTPS revers proxy and followed the documentation for docker on the website. But I can't connect to Elsa. This is my `docker-compose` configuration:

```
    elsa3:
        image: elsaworkflows/elsa-server-and-studio-v3:latest
        container_name: elsa3
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            HTTP_PORTS: 8080 
            HTTP__BASEURL: https://elsa.${LOCATION_DOMAIN}
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.elsa.loadbalancer.server.port=8080"
            - "traefik.http.routers.elsa.rule=Host(`elsa.${LOCATION_DOMAIN}`)"
            - "traefik.http.routers.elsa.entrypoints=https" 
```

### Proposed Documentation Changes
Update the documentation to include description on how to use Elsa with a reverse proxy. In addition I also did not found how I can make the content persistent (once I can reach it).

**Comment by jwillmer** [comment]
Using the following config:
```
    elsa3:
        image: elsaworkflows/elsa-server-and-studio-v3-3-0-preview:latest
        container_name: elsa3
        restart: always
        networks:
            traefik_proxy:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            HTTP_PORTS: 8080
            HOSTING__BASEURL: https://elsa.${LOCATION_DOMAIN}
            HOSTING__BASEPATH:
            DATABASEPROVIDER: PostgreSql
            CONNECTIONSTRINGS__POSTGRESQL: Host=postgres;Port=5432;Database=elsa3;Username=${POSTGRESUSER};Password=${POSTGRESPW}
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.elsa.loadbalancer.server.port=8080"
            - "traefik.http.routers.elsa.rule=Host(`elsa.${LOCATION_DOMAIN}`)"
            - "traefik.http.routers.elsa.entrypoints=https" 
```

I get the following log output:
```
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
```

and a `404 page not found`.

**Comment by sfmskywalker** [comment]
Can you share with me your full compose file and the irk you are trying to open in the browser?

**Comment by jwillmer** [comment]
The full compose is a little bit complex. But I guess you are after the traefik configuration. We use valid SSL certificates and reroite everything to port 443/SSL. The apps should not care about that but it seams like that elsa tries to use SSL if I define a `https` domain.

```
    traefik:
        image: traefik
        container_name: traefik
        restart: always
        command:
            #- "--log.level=DEBUG"
            - "--api.dashboard=true"
            - "--providers.docker=true"
            - "--ping=true"
            - "--ping.entryPoint=ping"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=traefik_proxy"
            - "--entryPoints.ping.address=:8081"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.https.address=:443"
            - "--entrypoints.https.http.tls=true"
            - "--entrypoints.https.http.tls.certresolver=letsencrypt"
            - "--entrypoints.https.http.tls.domains[0].main=${LOCATION_DOMAIN}"
            - "--entrypoints.https.http.tls.domains[0].sans=*.${LOCATION_DOMAIN}"
            - "--entrypoints.http.http.redirections.entryPoint.to=https"
            - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
            - "--certificatesresolvers.letsencrypt.acme.email=info@${LOCATION_DOMAIN}"
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
        environment:
            - CF_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
        networks:
            - default
            - traefik_proxy
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
        volumes:
            - "letsencrypt:/letsencrypt"
            - /var/run/docker.sock:/var/run/docker.sock:ro
```
