### ISSUE TITLE
[BUG] Oracle provider in 3.3.2-rc1

### ISSUE THREAD

**Issue by b0rv3g4r4** [elsa-workflows/elsa-core#6355]
## Description
Im trying to start a fresh elsa instance in 3.3 with Oracle provider but im getting this error:

The property 'SerializedPayload' cannot be added to the type 'StoredTrigger' because no property type was specified and there is no corresponding CLR property or field. To add a shadow state property, the property type must be specified.

I think that the 3_3 migrations are wrong for oracle. Looking the types in SetupForOracle dont match with the migrations.

**Comment by sfmskywalker** [comment]
Could you elaborate a bit on the types that you noticed that don't match with the migrations? I haven't spot anything strange so far.

**Comment by b0rv3g4r4** [comment]
For example the SerializedPayload, in the migrations are defined as NVARCHAR(2000) but this fields need to be NCLOB as defined in SetupForOracle

![Image](https://github.com/user-attachments/assets/37417143-6f8b-4968-b9a5-fa97d8f429e5)

**Comment by sfmskywalker** [comment]
I see, yes. I have pushed a branch that fixes the migrations, and is being built here: https://github.com/elsa-workflows/elsa-core/actions/runs/13063460256

I haven't figured out yet what connection string to use to successfully connect to the Oracle container (FREE), so I haven't been able to test it at runtime yet. Perhaps you can help me?

This is my compose:

```yaml
  oracle:
      image: container-registry.oracle.com/database/free:latest
      container_name: oracle
      environment:
        ORACLE_PDB: ORCLPDB1
        ORACLE_PWD: elsa
      ports:
        - "1521:1521"
        - "5500:5500"
      volumes:
        - oracle-data-free:/opt/oracle/oradata
      shm_size: '1g'
```

The Oracle container has started successfully and I am able to access its terminal and issue SQL commands.

However, the following connection string doesn't work - the driver complaints about an unknown user:

```
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01435: user does not exist
```

This is my connection string:

```
User Id=SYSTEM;Password=elsa;Data Source=localhost:1521/FREE;
```

Any suggestions?

**Comment by b0rv3g4r4** [comment]
I have an oracle XE like this:


```yaml
version: "3.7"

services:
  oracle:
    container_name: oracle-db
    image: registry.gitlab.com/smartdevops/avatel/oracle-xe:latest
    volumes:
      - ./oracle-data:/opt/oracle/oradata
      - ./oracle-startup:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: secret
    ports:
      - 1521:1521
      - 5500:5500
```

Then i have an initial sql to create the user and schema in the oracle-startup folder


```sql
