### ISSUE TITLE
Docker-Compose Configuration

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#839]
How do I configure elsa in docker-compose when it is running behind a proxy?

This is what I came up with so far:

```
    traefik:
        image: traefik:v2.2
        container_name: traefik
        restart: always
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false" 
            - "--entrypoints.https.address=:443"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.http.http.redirections.entryPoint.to=https"
            - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
            - ...
        ports:
            - "80:80"         
            - "443:443"
        volumes:
            - "letsencrypt:/letsencrypt"
            - /var/run/docker.sock:/var/run/docker.sock:ro

    elsa-dashboard:
        image: ghcr.io/elsa-workflows/elsa-core/elsa-dashboard:latest
        container_name: elsa-dashboard
        environment:
            - Elsa:Http:BaseUrl=http://localhost
            - Dashboard:ElsaServerUrl=https://elsa.${DOMAINNAME}
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.elsa.loadbalancer.server.port=80"
            - "traefik.http.routers.elsa.rule=Host(`elsa.${DOMAINNAME}`)"
            - "traefik.http.routers.elsa.entrypoints=https" 
```
